import os

TELEGRAM_API_KEY = os.getenv("TELEGRAM_API_KEY")
CONTACT_EMAIL = os.getenv("CONTACT_EMAIL")
ASSINATURA_LINK = os.getenv("ASSINATURA_LINK")
PROPAGA_FEEDBACK_CHAT_ID = os.getenv("PROPAGA_FEEDBACK_CHAT_ID").split()
